[package]
name = "venturi"
version = "0.1.3"
edition = "2021"

[features]
# defines that benchmark tests be included in the build, required unstable channel
benchmark = []


[dependencies]
ndarray = "0.15"
rand = "0.8"
byteorder= "1.4"
clap = { version = "3.1.18", features = ["derive"] }
